### ISSUE TITLE
Improve Prerequisite section

### ISSUE THREAD

**Issue by pacostas** [nodeshift/tutorial#20]
On each url in the Prerequisites section, point to the corresponding section of the setting up section

**Comment by pacostas** [comment]
On section: Setting up
We cover installation process:

**Podman** Under sub-section: Starting Podman Machine
* linux: no
* Mac: no
* Windows: yes -> Install podman desktop and will guide you to install podman 

**Minikube** Under sub-section: Starting kubernetes
* Mac: no
* Windows: yes
* linux: no

**Helm** Under sub-ection: Installing Helm 
* linux: yes
* windows: yes
* mac: yes

At the moment we have the installation process on the prerequisites section.
We can add another section called Installation as installing and starting the services is mixed in one place in an inconsistent way. Even if sometimes on the installation section we only have just the link from the prerequisites, I think that creating a separate installation section will be easier for people to follow, which can also be combined easier with the instructions for installing some of the packages from a usb stick.

(super minor but) at the end of each sub-section in the installation, we can add a link for jumping back to the prerequisites section for having a clear overview of what the user has installed or not.

**Comment by mhdawson** [comment]
@pacostas I think we've completed this and it would be closed?
