### ISSUE TITLE
windows admin access

### ISSUE THREAD

**Issue by pacostas** [nodeshift/tutorial#22]
One other thing is that at least on windows it does require admin access to install the pieces needed (podman which requires both hyperv and wsl). I think we better try to get a message to participants in advance with the warning that admin access is needed, and that they should if at all possible install X,Y,Z in advance depending on the platform

_Originally posted by @mhdawson in https://github.com/nodeshift/tutorial/issues/19#issuecomment-1233436614_

**Comment by pacostas** [comment]
Indeed. Despite that, I believe all windows developers have wsl and hyper-v enabled.
+1 for the disclaimer about the admin access

**Comment by mhdawson** [comment]
Ok, we've discussed this, and I think it's understood admin access will be needed and we'll message that. Added in https://github.com/nodeshift/tutorial/pull/31
