### ISSUE TITLE
One more, do we even need Podman Desktop?

### ISSUE THREAD

**Issue by pacostas** [nodeshift/tutorial#23]
One more, do we even need podman desktop? I don't think we use or mention it in the workshop (although we might want to change that).  I wondered about that as the installation instructions don't include the link for Mac, although it is available.

_Originally posted by @mhdawson in https://github.com/nodeshift/tutorial/issues/19#issuecomment-1233466789_

**Comment by mhdawson** [comment]
I see the updated windows instructions use it.That might answer the question.  It's probably good to highlight podman desktop from the RH perpsective even if the workshop can run without it.

**Comment by pacostas** [comment]
Podman Desktop is being used as part of the podman installation to install all the prerequistes (hyper-v, wsl etc.) and to initialize/run podman machine. We were also using Docker Desktop to install minikube and to expose docker images on it. Podman Desktop does not support minkube installation so far.

**Comment by pacostas** [comment]
Podman Desktop is planning to support kubernetes providers in the near future. https://github.com/containers/podman-desktop/issues/29

**Comment by mhdawson** [comment]
We've discussed and are happy with what is in the workshop right now, closing.
