### ISSUE TITLE
Windows flow - 3 comments

### ISSUE THREAD

**Issue by pacostas** [nodeshift/tutorial#24]
Had a few specific comments but overall on Windows seemed to flow ok.

Three things we should think about for follow on PRs

1) can we easily alias `minikube kubectl --` to `kubectl` on all platforms. If so we may want to do that to make most of the instructions more kubernetes generic.
2) Should we add a registry to podman instead of using `$ minikube image push $(minikube ip):42631/nodeserver`, again that might be more kubenetes generic.
3) If 1 and 2) work out then I wonder if we could have 2 options.  1 to install minikube and 1 to use the RH sandbox. If the rest of the instructions just used kubectl then there might not be any other differences in the instructions other than how you set up kubectl (aliast for minikube or alias to oc for sandbox) and the registry set up for podman (registry in minikube or your registry in sandbox)

_Originally posted by @mhdawson in https://github.com/nodeshift/tutorial/issues/19#issuecomment-1233435402_

**Comment by mhdawson** [comment]
I think we've explored the different issues mentioned here.  closing
