### ISSUE TITLE
Downloading and installing Podman takes lots of time

### ISSUE THREAD

**Issue by pacostas** [nodeshift/tutorial#25]
Downloading and installing Podman takes lots of time
* depends also on the network but with 50mbps speed it took me something like 10-15 minutes.
* People being on the same network, will make it even slower.

**Comment by pacostas** [comment]
Re-validated if we can pre-download any binaries

**Comment by pacostas** [comment]
* For helm we already use a binary file

* Installing podman through a binary is not convenient https://github.com/containers/podman/issues/8660 and at the end of the day we only save approximately 80 mb

* Minikube has two parts. 1st part is the installation, where we already use a binary file ~70 mb . 2nd part is the setup (`minikube start`) where in that case downloads a .tar.lz4 file ~430 mb). In the 2nd part before downloading the .tar.lz4 file (which contains the kubernetes), looks under the ~/minikube/cache/preloaded-tarball directory if the file already exists. If exists then it does not download it and uses the downloaded file.  We can easily put that on a stick or localhost it. Although I didnt find the registry to browse on the available .tar.gz files and download them all at once to put them on a usb or serve them from a localhost and and the users just copy/paste them under the `~/minikube/cache/preloaded-tarball`, although I found the below function which generates the url according to minikube specs. https://github.com/kubernetes/minikube/blob/3d3214275acf191a57731e93fae75132b559e031/pkg/minikube/download/preload.go#L92-L94

  * We might need to lock down minikube version due to kubernetes happens to be different on each minikube version which results in different version from the one being stored on the usbs/localhost or another solution would be to lock down the kubernetes version with the version that we have on the usb by using  `--kubernetes-version=v1.24.3` flag, but that is something that we havent tested (minikube version with different kubernetes version).Topic about shipped  minikube/ kubernetes version https://minikube.sigs.k8s.io/docs/handbook/config/#selecting-a-kubernetes-version 

console output:

```
$ minikube start 
...
...
I0908 15:05:02.830224   18475 download.go:101] Downloading: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/v18/v1.24.3/preloaded-images-k8s-v18-v1.24.3-containerd-overlay2-amd64.tar.lz4?checksum=md5:b71984cb143cf2df2a8f3f6381f67a11 -> /home/costas/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.24.3-containerd-overlay2-amd64.tar.lz4
...
```

**Comment by mhdawson** [comment]
For the workshop we have a plan to bring some of the components on USB stick as a backup in order to address this. Closing.
