### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by pacostas** [nodeshift/tutorial#27]
Validate flow also on windows 11

**Comment by pacostas** [comment]
From @mhdawson comment https://github.com/nodeshift/tutorial/pull/29#issuecomment-1251543485 continuing discussion here

@pacostas I'm not following the comments. I thought from the chat discussion it had worked on windows 11? But from the comment above it sounds like maybe not, or am I misunderstanding?

**Comment by pacostas** [comment]
@mhdawson 
I have tested it on windows 11 home edition with `minikube start --driver=podman --container-runtime=containerd` The tutorial uses `minikube start` which results in using hyper-v as container runtime and that is why this command cannot run on windows home. So answer is, it worked on windows 11 and specificallly on home edition. I'm quite sure that on pro it will work too either using `miniube start` which is the current or either using  `minikube start --driver=podman --container-runtime=containerd` 
The question is which one should we choose? the later covers all windows editions but it has the drawback that we to cover podman installation due to podman desktop installation is not quite right at the moment. I opened an issue here https://github.com/containers/podman-desktop/issues/480

**Comment by mhdawson** [comment]
> podman desktop installation is not quite right at the moment.

The current instructions rely on podman desktop right? Are you saying that we'd have to remove that?

**Comment by pacostas** [comment]
If someone has windows home, then it's good to remove that and do the installation with podman, which is even easier as podman handles to install "hyper-v/Virtual Platform machine" and wsl with just one command.
Also if someone has windows home, we have to change the instructions to `minikube start --driver=podman --container-runtime=containerd` instead of `minikube start`

**Comment by pacostas** [comment]
yeap!
